"""Source instruction/resource paths, projected event-MIP, full graph verification."""
from pathlib import Path
import json,subprocess,sys,time,datetime,hashlib,math
ROOT=Path(__file__).parent
sys.path.insert(0,str(ROOT.parent/'mip_microarchitecture_001'))
from formulate import Model
LABELS=['staged32','staged48','staged64','direct']

def source_cache_counter():
    folder=ROOT.parent/'step7_cache_path_correction_001'
    receipt=json.loads((folder/'source_pc_corrected_cache_v2.json').read_text())
    assert receipt['source_sha256']==hashlib.sha256((folder/'cache_predict_pc_v2.py').read_bytes()).hexdigest(), 'Cache counter source changed: regenerate receipt'
    case=next(c for c in receipt['cases']if c['K']==3072)
    assert case['requests']==144*96*512
    return case['L1_sector_misses_to_L2']

def graph(label,sector_policy="source_cache"):
    path=json.loads((ROOT/f'{label}_instructions.json').read_text());events=[]
    for line in(ROOT/f'{label}.events').read_text().splitlines():
        t,end,cap,w,index,pc,kind=map(int,line.split());events.append(dict(t=t,end=end,cap=cap,w=w,index=index,pc=pc,kind=kind))
    names=['origin'];arcs=[];values=[0];pred=[None]
    def node(name):names.append(name);values.append(0);pred.append(None);return len(names)-1
    def edge(a,b,lag,basis):
        assert a<b,(a,b,basis)
        arcs.append((a,b,lag,basis));v=values[a]+lag
        if v>=values[b]:values[b]=v;pred[b]=len(arcs)-1
    writes=[{}for _ in range(4)];readers=[{}for _ in range(4)];tags=[{}for _ in range(4)];prev=[0]*4;lastSM=0;queues={k:[]for k in(1,2,3,4,6)};release=[0]*4;arrivals=[];drains=[];record=[]
    for e in events:
        w=e['w'];i=path[e['index']];v=node(f"{label}.w{w}.i{e['index']}.pc{i['pc']:x}.issue");c=node(f"{label}.w{w}.i{e['index']}.result")
        edge(0,v,0,'origin_nonnegative')
        if prev[w]:edge(prev[w],v,1,'warp_program_issue')
        if lastSM:edge(lastSM,v,1,'fixed_RR_SM_issue')
        if release[w]:edge(release[w],v,0,'CTA_release')
        for r in i['src']:
            if r in writes[w]:edge(writes[w][r],v,0,'register_source_ready')
        for r in i['dst']:
            if r in writes[w]:edge(writes[w][r],v,0,'register_WAW')
            if r in readers[w]:edge(readers[w][r][0],v,readers[w][r][1],'register_WAR_capture')
        for b in range(6):
            if(i['req']>>b)&1 and b in tags[w]:edge(tags[w][b][0],v,tags[w][b][1],'encoded_barrier_req')
        delay=e['end']-e['t'];capture=e['cap']-e['t']
        # All differences above are generated by explicit primitive parameters,
        # never GPU timestamps. Assert those durations against source class.
        expected={0:1,1:352 if label=='direct'else 340,2:1,3:29,4:32,5:1,6:28+i['packages']}[i['kind']];assert delay==expected
        edge(v,c,delay,'primitive_'+str(i['kind']))
        for r in i['dst']:writes[w][r]=c
        for r in i['src']:readers[w][r]=(v,capture)
        for tag,vertex,lag,due in[(i['wr'],c,0,e['end']),(i['rd'],v,capture,e['cap'])]:
            if tag>=0 and(tag not in tags[w]or due>=tags[w][tag][2]):tags[w][tag]=(vertex,lag,due)
        kind=i['kind']
        if kind in queues:
            q=queues[kind];interval={1:1,2:1,3:1,4:8,6:i['packages']}[kind];slots={1:32,2:32,3:4,4:2,6:32}[kind]
            if q:edge(q[-1][0],v,q[-1][2],'service_interval')
            if len(q)>=slots:edge(q[-slots][1],v,0,'finite_pending_slots')
            q.append((v,c,interval))
        if kind in(1,2,6):drains.append(c)
        if kind==5:
            arrivals.append(v)
            if len(arrivals)==4:
                b=node(f'{label}.barrier{len(record)}.release')
                for a in arrivals:edge(a,b,1,'CTA_collective_release')
                for a in drains:edge(a,b,1,'CTA_memory_drain')
                release=[b]*4;arrivals=[];drains=[]
        prev[w]=v;lastSM=v;record.append((v,c,e))
    finish=node(label+'.whole_complete')
    for v,c,e in record:edge(c,finish,7607,'startup_dispatch_output_tail')
    # Source-prior 48-slice one-sector-admission/edge aggregate. This is a
    # resource constraint of the provisional model, not recovered hardware.
    sectors=(512 if sector_policy=='requested'else 128)if label=='direct'else 128
    requests=source_cache_counter()if label=='direct'and sector_policy=='source_cache'else 144*96*sectors
    edge(0,finish,7607+math.ceil(requests/48),'global_slice_service_capacity_prior')
    incoming=[[]for _ in names]
    for ai,(a,b,lag,basis)in enumerate(arcs):incoming[b].append(ai)
    values=[0]*len(names);pred=[None]*len(names)
    for b in range(1,len(names)):
        for ai in incoming[b]:
            a,_,lag,_=arcs[ai];candidate=values[a]+lag
            if candidate>=values[b]:values[b]=candidate;pred[b]=ai
    patharcs=[];v=finish
    while v:
        a=pred[v];assert a is not None;patharcs.append(a);v=arcs[a][0]
    patharcs.reverse()
    mismatch=[(e['w'],e['index'],values[v],e['t'])for v,c,e in record if values[v]!=e['t']]
    instruction_tail=max((ai for ai,(a,b,lag,basis)in enumerate(arcs)if b==finish and basis=='startup_dispatch_output_tail'),key=lambda ai:values[arcs[ai][0]]+arcs[ai][2])
    auxiliary=[instruction_tail];v=arcs[instruction_tail][0]
    while v:
        a=pred[v];assert a is not None;auxiliary.append(a);v=arcs[a][0]
    auxiliary.reverse()
    return dict(auxiliary=auxiliary,label=label,names=names,arcs=arcs,values=values,finish=finish,path=patharcs,earliest=values[finish],event_checks=len(record),mismatches=mismatch[:20],mismatch_count=len(mismatch))

def main():
    begin=time.perf_counter();policy=sys.argv[1]if len(sys.argv)>1 else'source_cache';graphs=[graph(label,policy)for label in LABELS];built=time.perf_counter();m=Model();z=[m.var('select_'+g['label'],0,1,True)for g in graphs];m.constraint({x:1 for x in z},lo=1,hi=1);H=1000000;finish=m.var('whole_complete',0,H,False)
    retained=[]
    for branch,g in enumerate(graphs):
        prev=m.var(g['label']+'.origin',0,0,False);verts=[]
        for a in g['path']:
            src,dst,lag,basis=g['arcs'][a];v=m.var(g['names'][dst],0,H,False)
            B=H+lag;m.constraint({v:1,prev:-1,z[branch]:-B},lo=lag-B);prev=v;verts.append(dict(src=g['names'][src],dst=g['names'][dst],lag=lag,basis=basis))
        m.constraint({finish:1,prev:-1,z[branch]:-H},lo=-H);retained.append(verts)
        if g['label']=='direct':
            prev=m.var('direct.instruction_origin',0,0,False)
            for a in g['auxiliary']:
                src,dst,lag,basis=g['arcs'][a];v=m.var(g['names'][dst]+'.instruction_path',0,H,False)
                B=H+lag;m.constraint({v:1,prev:-1,z[branch]:-B},lo=lag-B);prev=v
            m.constraint({finish:1,prev:-1,z[branch]:-H},lo=-H)
    solve_start=time.perf_counter();r=m.solve({finish:1},30);solved=time.perf_counter();assert r.status==0,r.message
    selected=next(i for i,x in enumerate(z)if r.x[x]>.5);assert round(r.x[finish])==min(g['earliest']for g in graphs)
    # Full source graph earliest times satisfy every retained and omitted arc;
    # exact finite-domain projection proof requires feasible full expansion.
    for g in graphs:assert all(g['values'][b]>=g['values'][a]+lag for a,b,lag,_ in g['arcs'])
    result={'state':'postmeasurement_source_cache_layer_correction'if policy!='requested'else'postconfirmation_gate_bound_audit_no_numeric_refit','frozen_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sector_policy':policy,'cache_counter_provenance':{'source':'../step7_cache_path_correction_001/cache_predict_pc_v2.py','receipt':'../step7_cache_path_correction_001/source_pc_corrected_cache_v2.json','direct_L2_requests':source_cache_counter(),'classification':'postmeasurement integration, not a new frozen forecast'}if policy=='source_cache'else None,'selected_path':graphs[selected]['label'],'selected_cycles':round(r.x[finish]),'selected_us_at2940':r.x[finish]/2940,'branches':[{'label':g['label'],'cycles':g['earliest'],'us_at2940':g['earliest']/2940,'full_vertices':len(g['names']),'full_arcs':len(g['arcs']),'retained_critical_event_arcs':len(g['path']),'source_executor_issue_checks':g['event_checks'],'graph_vs_executor_mismatch_count':g['mismatch_count'],'first_mismatches':g['mismatches']}for g in graphs],'MIP':{'variables':len(m.names),'integer_variables':sum(m.integer),'constraints':len(m.rows),'solve_seconds':solved-solve_start,'gap':float(r.mip_gap)},'cost':{'full_graph_build_seconds':built-begin,'projected_MIP_build_seconds':solve_start-built,'total_seconds':solved-begin},'retained_paths':retained,'direct_retained_instruction_path':[{'src':graphs[-1]['names'][graphs[-1]['arcs'][a][0]],'dst':graphs[-1]['names'][graphs[-1]['arcs'][a][1]],'lag':graphs[-1]['arcs'][a][2],'basis':graphs[-1]['arcs'][a][3]}for a in graphs[-1]['auxiliary']],'full_graph_expansion_feasible':True,'scope':'Finite4path source-assistedfixedRR instruction-order domain. Critical-eventprojection exact for these sourcegraph branches viafullfeasibleexpansion; notallpossiblekernels/schedules. NoGPUruntimecoefficients.48sliceaggregatecapacitypriornotrecoveredhardware. Direct352batchcompositeappliedperLDasexplicittransferprior; staged340scopedprior,ALU/capture/servicepriorsunidentified. Predicate/uniform/encodedcontrolannotationsignored. Warmtrafficconditional; cachemissstate/serviceunknown, notallhitguarantee.','source_hashes':{n:hashlib.sha256((ROOT/n).read_bytes()).hexdigest()for n in['data_path_mip.py','instruction_executor.hpp','extract_instructions.py','benchmark.cu']}}
    (ROOT/('integrated_source_cache_mip.json'if policy=='source_cache'else 'cache_layer_model_update.json'if policy!='requested'else'model_representation_audit_v3.json')).write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:v for k,v in result.items()if k not in['retained_paths','direct_retained_instruction_path']}))
if __name__=='__main__':main()
