#pragma once
#include "units.hpp"
#include <optional>
namespace timing {
inline unsigned slice_of(uint32_t address,unsigned slices,bool hashed=false){uint32_t l=address/128;return (hashed?(l^(l>>7)^(l>>13)):l)%slices;}
struct CacheOffer{bool valid=false;uint32_t id=0,address=0;uint8_t mask=255;};
struct L2Input{std::vector<CacheOffer> read,write;std::vector<bool> read_ready,write_ready;bool backing_ready=false,store_ready=false;std::optional<uint32_t> backing_return,store_return;explicit L2Input(unsigned sms):read(sms),write(sms),read_ready(sms,true),write_ready(sms,true){}};
struct L2Output{std::vector<bool> read_ready,write_ready,read_valid,write_valid;std::vector<uint32_t> read_id,write_id;CacheOffer backing,store;unsigned owners=0,mshrs=0;explicit L2Output(unsigned sms):read_ready(sms),write_ready(sms),read_valid(sms),write_valid(sms),read_id(sms),write_id(sms){}};
class L2Slice {
 struct Owner{bool live=false,done=false,write=false,sent=false;unsigned client=0;int mshr=-1;uint32_t id=0,internal=0,address=0;uint8_t mask=0;Cycle due=0;};
 struct Miss{bool live=false,sent=false;unsigned set=0,way=0,sector=0;uint32_t address=0,id=0;};
 struct Line{bool valid=false;uint32_t tag=0;uint8_t sectors=0;};
 struct Lookup{unsigned set=0,sector=0;uint32_t tag=0;int way=-1,join=-1;bool hit=false,admissible=false;};
 unsigned sms,sets,ways,stride,hit_delay;bool hash_mapping=false;std::vector<Owner> owner;std::vector<Miss> miss;std::vector<Line> lines;std::vector<unsigned> victim;std::vector<int> response;
 unsigned admission=0,backend_cursor=0;uint32_t next_id=0;CacheOffer offer;bool offer_write=false;int offer_slot=0;Cycle cycle=0;
 bool pinned(unsigned s,unsigned w)const{for(auto m:miss)if(m.live&&m.set==s&&m.way==w)return true;return false;}
 Lookup lookup(const CacheOffer& r,int free_miss)const{Lookup x;if(!r.valid)return x;x.set=(r.address/128/stride)%sets;x.tag=hash_mapping?r.address/128:r.address/(128*sets*stride);x.sector=(r.address>>5)&3;int match=-1;for(unsigned w=0;w<ways;w++)if(line(x.set,w).valid&&line(x.set,w).tag==x.tag)match=w;x.way=match;for(unsigned w=0;w<ways;w++)if(x.way<0&&!line(x.set,w).valid&&!pinned(x.set,w))x.way=w;for(unsigned o=0;o<ways;o++){unsigned w=(victim[x.set]+o)%ways;if(x.way<0&&!pinned(x.set,w))x.way=w;}x.hit=match>=0&&(line(x.set,match).sectors&(1<<x.sector));for(unsigned m=0;m<miss.size();m++)if(miss[m].live&&miss[m].address==r.address)x.join=m;x.admissible=!(r.address&31)&&(x.hit||x.join>=0||(free_miss>=0&&x.way>=0));return x;}
 const Line& line(unsigned s,unsigned w)const{return lines[s*ways+w];}Line& line(unsigned s,unsigned w){return lines[s*ways+w];}
 static int free_owner(const std::vector<Owner>& v){for(unsigned i=0;i<v.size();i++)if(!v[i].live)return i;return -1;}
 static int free_miss(const std::vector<Miss>& v){for(unsigned i=0;i<v.size();i++)if(!v[i].live)return i;return -1;}
 int select(const L2Input& in,int fm,int fo)const{if(fo<0)return -1;for(unsigned off=0;off<2*sms;off++){unsigned c=(admission+off)%(2*sms);if(c<sms){if(in.read[c].valid&&lookup(in.read[c],fm).admissible)return c;}else if(in.write[c-sms].valid)return c;}return -1;}
public:
 uint64_t requests=0,hits=0,misses=0,merges=0,fills=0;unsigned peak_owners=0,peak_mshrs=0;
 L2Slice(unsigned ns,unsigned nsets,unsigned nw,unsigned no,unsigned nm,unsigned st,unsigned hd,bool hashed=false):sms(ns),sets(nsets),ways(nw),stride(st),hit_delay(hd),hash_mapping(hashed),owner(no),miss(nm),lines(nsets*nw),victim(nsets),response(2*ns,-1){}
 void warm_range(uint32_t first,uint64_t bytes,unsigned slice_index){if((first&127)||(bytes&127))throw std::runtime_error("warm range must cover full aligned cache lines");for(uint64_t a=first;a<uint64_t(first)+bytes;a+=128){if(slice_of(uint32_t(a),stride,hash_mapping)!=slice_index)continue;unsigned set=(a/128/stride)%sets;uint32_t tag=hash_mapping?a/128:a/(128*sets*stride);int slot=-1;for(unsigned w=0;w<ways;w++)if(line(set,w).valid&&line(set,w).tag==tag)slot=w;for(unsigned w=0;w<ways;w++)if(slot<0&&!line(set,w).valid)slot=w;if(slot<0)throw std::runtime_error("warm inputs exceed assumed set associativity");auto& l=line(set,slot);l.valid=true;l.tag=tag;l.sectors=15;victim[set]=(slot+1)%ways;}}
 Cycle now()const{return cycle;}
 L2Output eval(const L2Input& in)const{L2Output out(sms);for(auto o:owner)out.owners+=o.live;for(auto m:miss)out.mshrs+=m.live;int c=select(in,free_miss(miss),free_owner(owner));if(c>=0){if(unsigned(c)<sms)out.read_ready[c]=true;else out.write_ready[c-sms]=true;}for(unsigned c=0;c<2*sms;c++)if(response[c]>=0){if(c<sms){out.read_valid[c]=true;out.read_id[c]=owner[response[c]].id;}else{out.write_valid[c-sms]=true;out.write_id[c-sms]=owner[response[c]].id;}}if(offer.valid){if(offer_write)out.store=offer;else out.backing=offer;}return out;}
 Cycle wake()const{Cycle t=UINT64_MAX;unsigned no=0,nm=0;for(auto o:owner)no+=o.live;for(auto m:miss)nm+=m.live;if(no>peak_owners||nm>peak_mshrs)return cycle;if(offer.valid)return cycle;for(unsigned c=0;c<2*sms;c++)if(response[c]>=0)return cycle;for(auto o:owner)if(o.live&&o.done)t=std::min(t,std::max(cycle,o.due));for(auto m:miss)if(m.live&&!m.sent)return cycle;for(auto o:owner)if(o.live&&o.write&&!o.sent)return cycle;return t;}
 void advance_to(Cycle t){if(t<cycle||t>wake())throw std::runtime_error("cache jump would skip an internal event");cycle=t;}
 void edge(const L2Input& in){auto old_owner=owner;auto old_miss=miss;auto old_response=response;auto old_offer=offer;auto old_kind=offer_write;auto out=eval(in);int fm=free_miss(old_miss),fo=free_owner(old_owner),selected=select(in,fm,fo);int ret=-1,wret=-1;for(unsigned m=0;m<old_miss.size();m++)if(in.backing_return&&old_miss[m].live&&old_miss[m].sent&&old_miss[m].id==*in.backing_return)ret=m;for(unsigned o=0;o<old_owner.size();o++)if(in.store_return&&old_owner[o].live&&old_owner[o].write&&old_owner[o].sent&&!old_owner[o].done&&old_owner[o].internal==*in.store_return)wret=o;peak_owners=std::max(peak_owners,out.owners);peak_mshrs=std::max(peak_mshrs,out.mshrs);
 for(unsigned c=0;c<2*sms;c++){if(old_response[c]<0){for(unsigned o=0;o<old_owner.size();o++)if(old_owner[o].live&&old_owner[o].done&&cycle>=old_owner[o].due&&old_owner[o].client==c){response[c]=o;break;}}else if(c<sms?in.read_ready[c]:in.write_ready[c-sms]){owner[old_response[c]].live=false;response[c]=-1;}}
 if(selected>=0){unsigned c=selected,s=c%sms;auto request=c<sms?in.read[s]:in.write[s];for(auto o:old_owner)if(o.live&&o.client==c&&o.id==request.id)throw std::runtime_error("duplicate cache owner");Owner o;o.live=true;o.client=c;o.id=request.id;o.write=c>=sms;o.due=cycle;admission=(c+1)%(2*sms);if(o.write){if((request.address&31)||!request.mask)throw std::runtime_error("invalid store sector");o.internal=next_id++;o.address=request.address;o.mask=request.mask;}else{auto x=lookup(request,fm);++requests;if(x.hit){++hits;o.done=true;o.due=cycle+hit_delay;}else{++misses;if(x.join>=0){++merges;o.mshr=x.join;if(ret==x.join){o.done=true;o.mshr=-1;}}else{Miss m;m.live=true;m.id=next_id++;m.address=request.address;m.set=x.set;m.way=x.way;m.sector=x.sector;miss[fm]=m;o.mshr=fm;auto& l=line(x.set,x.way);if(!l.valid||l.tag!=x.tag){l.valid=true;l.tag=x.tag;l.sectors=0;}victim[x.set]=(x.way+1)%ways;}}}owner[fo]=o;}
 if(!old_offer.valid){int choice=-1;for(unsigned off=0;off<miss.size()+owner.size();off++){unsigned k=(backend_cursor+off)%(miss.size()+owner.size());if(k<old_miss.size()){if(old_miss[k].live&&!old_miss[k].sent){choice=k;break;}}else{auto o=old_owner[k-old_miss.size()];if(o.live&&o.write&&!o.sent){choice=k;break;}}}if(choice>=0){offer.valid=true;offer_write=unsigned(choice)>=miss.size();offer_slot=offer_write?choice-miss.size():choice;if(offer_write){auto o=old_owner[offer_slot];offer.id=o.internal;offer.address=o.address;offer.mask=o.mask;}else{auto m=old_miss[offer_slot];offer.id=m.id;offer.address=m.address;offer.mask=0;}backend_cursor=(choice+1)%(miss.size()+owner.size());}}else if(old_kind?in.store_ready:in.backing_ready){offer.valid=false;if(old_kind)owner[offer_slot].sent=true;else miss[offer_slot].sent=true;}
 if(in.backing_return){if(ret<0)throw std::runtime_error("unknown cache read return");++fills;miss[ret].live=false;auto m=old_miss[ret];line(m.set,m.way).sectors|=1<<m.sector;for(unsigned o=0;o<old_owner.size();o++)if(old_owner[o].live&&!old_owner[o].write&&!old_owner[o].done&&old_owner[o].mshr==ret){owner[o].done=true;owner[o].mshr=-1;}}
 if(in.store_return){if(wret<0)throw std::runtime_error("unknown cache store return");owner[wret].done=true;}++cycle;}
};
class GlobalCredits{unsigned sms,cursor=0;int64_t r=0,w=0,m=0,rr,wr,mr;public:GlobalCredits(unsigned ns,int64_t read,int64_t write,int64_t mixed):sms(ns),rr(read),wr(write),mr(mixed){}std::pair<std::vector<bool>,std::vector<bool>> permit(const std::vector<bool>&rv,const std::vector<bool>&wv)const{std::vector<bool>a(sms),b(sms);auto x=r+rr,y=w+wr,z=m+mr;for(unsigned off=0;off<sms;off++){auto s=(cursor+off)%sms;if(rv[s]&&x>=1024&&z>=1024){a[s]=true;x-=1024;z-=1024;}if(wv[s]&&y>=1024&&z>=1024){b[s]=true;y-=1024;z-=1024;}}return {a,b};}void idle_edges(Cycle n){r=std::min(r+int64_t(n)*rr,rr);w=std::min(w+int64_t(n)*wr,wr);m=std::min(m+int64_t(n)*mr,mr);cursor=(cursor+n)%sms;}void edge(const std::vector<bool>&accepted_read,const std::vector<bool>&accepted_write){auto x=r+rr,y=w+wr,z=m+mr;for(unsigned s=0;s<sms;s++){if(accepted_read[s]){x-=1024;z-=1024;}if(accepted_write[s]){y-=1024;z-=1024;}}r=std::min(x,rr);w=std::min(y,wr);m=std::min(z,mr);cursor=(cursor+1)%sms;}};
}
