#pragma once
#include "output_metadata.hpp"
namespace resident_event {
using output_event::Cycle;using output_event::never;using output_event::require;
struct Controller {
 enum State{IDLE,STAGE_SEND,STAGE_WAIT,COMPUTE_SEND,COMPUTE_WAIT,OUTPUT_SEND,OUTPUT_WAIT,RESULT};
 struct Context{State state=IDLE;uint32_t id=0,row=0,col=0,a=0,b=0,c=0;int stage=0;bool producer=false,consumer=false;unsigned seen=0;};
 int n,stages,N;std::vector<Context>ctx;output_event::Admission admission;int stage_owner=-1,stage_cursor=0,compute_owner=-1,compute_cursor=0,result_owner=-1,result_cursor=0,output_owner=-1,output_cursor=0,ordinal=0,write_cursor=0;bool store_wait=false;
 Controller(int contexts=11,int k=1536,int columns=2112):n(contexts),stages(k/32),N(columns),ctx(contexts),admission(contexts){}
 struct Inputs{bool reset=false,launch_valid=false,launch_legal=true,done_ready=false,staging_ready=false,staging_done=false,compute_ready=false,compute_done=false,scratch_ready=false,scratch_response=false,store_ready=false,store_response=false,write_valid=false,write_ready=false,scratch_grant=false;uint32_t launch_id=0,row=0,col=0,a=0,b=0,c=0,staging_context=0,staging_id=0,compute_context=0,compute_id=0,scratch_id=0,store_id=0;std::vector<bool>producer_release,consumer_release;std::vector<unsigned>consumer_arrival;};
 struct Signals{bool launch_ready=false,done=false,staging=false,compute=false,staging_done_ready=false,compute_done_ready=false,scratch=false,store=false,store_response_ready=false,scratch_response_ready=false;uint32_t done_id=0,done_context=0,stage_context=0,stage_id=0,compute_context=0,compute_id=0,store_id=0;std::array<uint32_t,32>store_addresses{};};
 Signals signals(const Inputs&i)const{Signals s;auto ad=admission.signals({});s.launch_ready=!i.reset&&ad.ready&&i.launch_legal;s.done=!i.reset&&result_owner>=0;if(result_owner>=0){s.done_id=ctx[result_owner].id;s.done_context=result_owner;}s.staging=!i.reset&&stage_owner>=0;if(stage_owner>=0){s.stage_context=stage_owner;s.stage_id=ctx[stage_owner].stage;}s.compute=!i.reset&&compute_owner>=0;if(compute_owner>=0){s.compute_context=compute_owner;s.compute_id=ctx[compute_owner].stage;}s.staging_done_ready=!i.reset&&i.staging_context<uint32_t(n)&&ctx[i.staging_context].state==STAGE_WAIT&&ctx[i.staging_context].producer;s.compute_done_ready=!i.reset&&i.compute_context<uint32_t(n)&&ctx[i.compute_context].state==COMPUTE_WAIT&&ctx[i.compute_context].consumer;s.scratch=!i.reset&&output_owner>=0&&ctx[output_owner].state==OUTPUT_SEND;s.store=!i.reset&&output_owner>=0&&i.scratch_response&&!store_wait;s.store_response_ready=!i.reset&&output_owner>=0&&store_wait;s.scratch_response_ready=i.store_response&&s.store_response_ready&&ordinal==31;s.store_id=output_owner>=0?output_owner*32+ordinal:0;for(int l=0;l<32;l++){int w=ordinal/8,index=32*(ordinal%8)+l,row=16*(w/2)+index/16,col=16*(w%2)+index%16;s.store_addresses[l]=output_owner>=0?ctx[output_owner].c+4*((ctx[output_owner].row*32+row)*N+ctx[output_owner].col*32+col):0;}return s;}
 int choose(State st,int cursor)const{for(int off=0;off<n;off++){int c=(cursor+off)%n;if(ctx[c].state==st)return c;}return -1;}
 void edge(const Inputs&i){if(i.reset){int contexts=n,k=stages*32,cols=N;*this=Controller(contexts,k,cols);return;}auto s=signals(i);auto ad=admission.signals({});auto old=ctx;auto next=ctx;require(!i.launch_valid||i.launch_legal,"invalid resident launch");int active=0;for(auto&c:old)active+=c.state!=IDLE;require(active==ad.resident&&4*active==ad.resident_warps,"resident conservation");bool admit=i.launch_valid&&s.launch_ready,retire=s.done&&i.done_ready;if(admit){require(old[ad.slot].state==IDLE,"resident slot mismatch");next[ad.slot]={STAGE_SEND,i.launch_id,i.row,i.col,i.a,i.b,i.c,0,old[ad.slot].producer,old[ad.slot].consumer,old[ad.slot].seen};}
 if(stage_owner<0)stage_owner=choose(STAGE_SEND,stage_cursor);else if(s.staging&&i.staging_ready){next[stage_owner].producer=false;next[stage_owner].state=STAGE_WAIT;stage_cursor=(stage_owner+1)%n;stage_owner=-1;}
 if(i.staging_done){require(i.staging_context<uint32_t(n)&&old[i.staging_context].state==STAGE_WAIT&&i.staging_id==uint32_t(old[i.staging_context].stage),"staging owner mismatch");if(s.staging_done_ready)next[i.staging_context].state=COMPUTE_SEND;}
 if(compute_owner<0)compute_owner=choose(COMPUTE_SEND,compute_cursor);else if(s.compute&&i.compute_ready){next[compute_owner].consumer=false;next[compute_owner].seen=0;next[compute_owner].state=COMPUTE_WAIT;compute_cursor=(compute_owner+1)%n;compute_owner=-1;}
 if(i.compute_done){require(i.compute_context<uint32_t(n)&&old[i.compute_context].state==COMPUTE_WAIT&&i.compute_id==uint32_t(old[i.compute_context].stage),"compute owner mismatch");if(s.compute_done_ready){auto&c=next[i.compute_context];if(old[i.compute_context].stage==stages-1)c.state=OUTPUT_SEND;else{c.stage++;c.state=STAGE_SEND;}}}
 for(int c=0;c<n;c++){if(c<int(i.producer_release.size())&&i.producer_release[c])next[c].producer=true;if(c<int(i.consumer_release.size())&&i.consumer_release[c])next[c].consumer=true;if(c<int(i.consumer_arrival.size())&&i.consumer_arrival[c])next[c].seen=old[c].seen|i.consumer_arrival[c];}
 if(i.write_valid&&i.write_ready)write_cursor=1;if(i.scratch_grant)write_cursor=0;
 if(output_owner<0){int choice=choose(OUTPUT_SEND,output_cursor);if(choice>=0){output_owner=choice;ordinal=0;store_wait=false;}}else{if(s.scratch&&i.scratch_ready)next[output_owner].state=OUTPUT_WAIT;if(i.scratch_response)require(i.scratch_id==uint32_t(output_owner),"scratch owner mismatch");if(s.store&&i.store_ready)store_wait=true;if(i.store_response)require(s.store_response_ready&&i.store_id==s.store_id,"store owner mismatch");if(i.store_response&&s.store_response_ready){store_wait=false;if(ordinal==31){next[output_owner].state=RESULT;output_cursor=(output_owner+1)%n;output_owner=-1;}else ordinal++;}}
 int retired=result_owner;if(result_owner<0)result_owner=choose(RESULT,result_cursor);else if(retire){next[result_owner].state=IDLE;result_cursor=(result_owner+1)%n;result_owner=-1;}admission.edge(false,admit,retire,retired,{});ctx=std::move(next);}
 Cycle wake(Cycle now)const{if(stage_owner<0&&choose(STAGE_SEND,stage_cursor)>=0||compute_owner<0&&choose(COMPUTE_SEND,compute_cursor)>=0||output_owner<0&&choose(OUTPUT_SEND,output_cursor)>=0||result_owner<0&&choose(RESULT,result_cursor)>=0)return now+1;return never;}
};
}
