#include "sm_event.hpp"
#include "grid_metadata.hpp"
#include "backing.hpp"
#include "sm_pool.hpp"
#include <iostream>
#include <chrono>
#include <memory>
using namespace timing;
int main(int argc,char**argv){try{int M=argc>1?std::stoi(argv[1]):2048,N=argc>2?std::stoi(argv[2]):2112,K=argc>3?std::stoi(argv[3]):1536;bool hashed=argc>4?std::stoi(argv[4]):false;unsigned sms=argc>5?std::stoi(argv[5]):170,slices=argc>6?std::stoi(argv[6]):48,contexts=argc>7?std::stoi(argv[7]):11;Cycle limit=argc>8?std::stoull(argv[8]):20000000;bool warm=argc>9?std::stoi(argv[9]):true;unsigned sets=argc>10?std::stoi(argv[10]):1024;constexpr uint32_t A=0,B=0x2000000,C=0x4000000;unsigned shared_slots=argc>13?std::stoi(argv[13]):2;std::vector<std::unique_ptr<sm_event::SM>> sm;for(unsigned s=0;s<sms;s++)sm.emplace_back(new sm_event::SM(contexts,M,N,K,shared_slots));std::vector<L2Slice>cache;for(unsigned s=0;s<slices;s++){cache.emplace_back(sms,sets,16,8,4,slices,4,hashed);if(warm){cache.back().warm_range(A,2ull*M*K,s);cache.back().warm_range(B,2ull*K*N,s);}}GlobalCredits credits(sms,37481,31056,49089);credits.idle_edges(2);Backing memory(slices);grid_event::Grid grid(sms,M,N);std::vector<sm_event::Input>si(sms);std::vector<sm_event::Signals>ss(sms);std::vector<L2Input>ci;for(unsigned s=0;s<slices;s++)ci.emplace_back(sms);std::vector<L2Output>cs;std::vector<int>heldread(sms,-1),heldwrite(sms,-1),selectedread(sms),selectedwrite(sms);std::vector<bool>rv(sms),wv(sms),acceptedr(sms),acceptedw(sms);std::vector<uint64_t>slice_reads(slices),slice_writes(slices);std::vector<bool>seen(size_t(M)*N);uint64_t checked=0,native=0;unsigned peak=0;auto start=std::chrono::steady_clock::now();grid_event::Grid::Inputs gi;gi.ready.resize(sms);gi.done.resize(sms);gi.done_id.resize(sms);gi.launch=true;gi.id=1;gi.a=A;gi.b=B;gi.c=C;gi.done_ready=false;grid.edge(gi);gi.launch=false;std::vector<Cycle> smwake(sms);for(unsigned s=0;s<sms;s++){si[s].a=A;si[s].b=B;si[s].c=C;ss[s]=sm[s]->signals(0,si[s]);smwake[s]=sm[s]->wake(0);}
SMPool pool(sms,argc>12?std::stoi(argv[12]):4);unsigned launches=argc>11?std::stoi(argv[11]):1;Cycle base=0;for(unsigned launch=0;launch<launches;launch++){for(Cycle local=0;local<limit;local++){Cycle t=base+local;
 gi.resident=0;pool.run([&](unsigned s){si[s]={};si[s].a=A;si[s].b=B;si[s].c=C;si[s].done_ready=false;if(t>=smwake[s])ss[s]=sm[s]->signals(t,si[s]);});for(unsigned s=0;s<sms;s++){gi.ready[s]=ss[s].launch_ready;gi.done[s]=ss[s].done;gi.done_id[s]=ss[s].done_id;gi.resident+=ss[s].resident;rv[s]=ss[s].read.valid;wv[s]=ss[s].write.valid;}peak=std::max(peak,unsigned(gi.resident));auto gs=grid.signals(gi);if(gs.launch_sm>=0){auto&i=si[gs.launch_sm];i.launch=true;i.id=gs.launch_id;i.row=gs.row;i.col=gs.col;i.a=A;i.b=B;i.c=C;}if(gs.done_sm>=0)si[gs.done_sm].done_ready=true;
 auto permits=credits.permit(rv,wv);for(unsigned sl=0;sl<slices;sl++){auto&x=ci[sl];std::fill(x.read.begin(),x.read.end(),CacheOffer{});std::fill(x.write.begin(),x.write.end(),CacheOffer{});std::fill(x.read_ready.begin(),x.read_ready.end(),false);std::fill(x.write_ready.begin(),x.write_ready.end(),false);x.backing_ready=x.store_ready=false;x.backing_return.reset();x.store_return.reset();}for(unsigned s=0;s<sms;s++){if(rv[s]&&permits.first[s]){auto p=ss[s].read;ci[slice_of(p.address,slices,hashed)].read[s]={true,p.id,p.address,p.mask};}if(wv[s]&&permits.second[s]){auto p=ss[s].write;ci[slice_of(p.address,slices,hashed)].write[s]={true,p.id,p.address,p.mask};}}
 cs.clear();for(unsigned sl=0;sl<slices;sl++)cs.push_back(cache[sl].eval(ci[sl]));auto bp=memory.prepare(t,cs);std::fill(acceptedr.begin(),acceptedr.end(),false);std::fill(acceptedw.begin(),acceptedw.end(),false);
 for(unsigned s=0;s<sms;s++){selectedread[s]=selectedwrite[s]=-1;for(unsigned sl=0;sl<slices;sl++){if(cs[sl].read_ready[s]){si[s].read_ready=true;acceptedr[s]=rv[s];if(rv[s])slice_reads[sl]++;}if(cs[sl].write_ready[s]){si[s].write_ready=true;acceptedw[s]=wv[s];if(wv[s])slice_writes[sl]++;}if(cs[sl].read_valid[s]&&selectedread[s]<0&&(heldread[s]<0||heldread[s]==int(sl)))selectedread[s]=sl;if(cs[sl].write_valid[s]&&selectedwrite[s]<0&&(heldwrite[s]<0||heldwrite[s]==int(sl)))selectedwrite[s]=sl;}if(selectedread[s]>=0)si[s].read_return=cs[selectedread[s]].read_id[s];if(selectedwrite[s]>=0)si[s].write_return=cs[selectedwrite[s]].write_id[s];auto ready=ss[s];if(selectedread[s]>=0){ci[selectedread[s]].read_ready[s]=ready.read_return_ready;heldread[s]=ready.read_return_ready?-1:selectedread[s];}if(selectedwrite[s]>=0){ci[selectedwrite[s]].write_ready[s]=ready.write_return_ready;heldwrite[s]=ready.write_return_ready?-1:selectedwrite[s];}native+=ready.native_issue;}
 for(unsigned sl=0;sl<slices;sl++){ci[sl].backing_ready=bp.read_ready[sl];ci[sl].store_ready=bp.write_ready[sl];ci[sl].backing_return=bp.read_return[sl];ci[sl].store_return=bp.write_return[sl];if(cs[sl].store.valid&&bp.write_ready[sl]){auto p=cs[sl].store;for(unsigned w=0;w<8;w++)if(p.mask&(1<<w)){uint64_t at=(uint64_t(p.address)+4*w-C)/4;if(at>=seen.size()||seen[at])throw std::runtime_error("duplicate or out-of-range C address");seen[at]=true;++checked;}}}
 pool.run([&](unsigned s){auto&i=si[s];bool external=i.launch||(i.done_ready&&ss[s].done)||(i.read_ready&&ss[s].read.valid)||(i.write_ready&&ss[s].write.valid)||i.read_return.has_value()||i.write_return.has_value();if(t>=smwake[s]||external){sm[s]->edge(t,i);sm_event::Input idle;idle.a=A;idle.b=B;idle.c=C;idle.done_ready=false;ss[s]=sm[s]->signals(t+1,idle);smwake[s]=sm[s]->wake(t+1);}});for(unsigned sl=0;sl<slices;sl++)cache[sl].edge(ci[sl]);memory.edge(t,cs,bp);credits.edge(acceptedr,acceptedw);grid.edge(gi);
 if(t%10000==9999||grid.state==grid_event::Grid::COMPLETE){double sec=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::cout<<"PROGRESS cycles="<<t+1<<" elapsed="<<grid.elapsed<<" dispatched="<<grid.dispatched<<" completed="<<grid.completed<<" checked="<<checked<<" native="<<native<<" host_seconds="<<sec<<" cycles_per_second="<<(t+1)/sec<<std::endl;}
 if(grid.state==grid_event::Grid::COMPLETE){if(checked!=uint64_t(M)*N)throw std::runtime_error("incomplete C address coverage");uint64_t req=0,hits=0,miss=0,merges=0,fills=0;for(auto&c:cache){req+=c.requests;hits+=c.hits;miss+=c.misses;merges+=c.merges;fills+=c.fills;}std::cout<<"FULL_CPP_PASS launch="<<launch<<" M="<<M<<" N="<<N<<" K="<<K<<" shared_slots="<<shared_slots<<" hashed="<<hashed<<" warm="<<warm<<" cycles="<<grid.elapsed<<" checked="<<checked<<" peak="<<peak<<" requests="<<req<<" hits="<<hits<<" misses="<<miss<<" merges="<<merges<<" fills="<<fills<<std::endl;std::cout<<"SLICE_READS";for(auto n:slice_reads)std::cout<<' '<<n;std::cout<<"\nSLICE_WRITES";for(auto n:slice_writes)std::cout<<' '<<n;std::cout<<std::endl;if(launch+1==launches)return 0;grid=grid_event::Grid(sms,M,N);gi.launch=true;gi.resident=0;grid.edge(gi);gi.launch=false;std::fill(seen.begin(),seen.end(),false);checked=native=peak=0;for(auto&cc:cache)cc.advance_to(t+2);credits.idle_edges(1);memory.idle_edges(1);base=t+2;break;}}if(grid.state!=grid_event::Grid::STARTUP){uint64_t pr=0,ph=0,pm=0,pf=0;for(auto&cc:cache){pr+=cc.requests;ph+=cc.hits;pm+=cc.misses;pf+=cc.fills;}std::cout<<"PREFIX_ONLY limit="<<limit<<" elapsed="<<grid.elapsed<<" requests="<<pr<<" hits="<<ph<<" misses="<<pm<<" fills="<<pf<<" native="<<native<<std::endl;return 2;}}
 uint64_t pr=0,ph=0,pm=0,pf=0;for(auto&cc:cache){pr+=cc.requests;ph+=cc.hits;pm+=cc.misses;pf+=cc.fills;}std::cout<<"PREFIX_ONLY limit="<<limit<<" elapsed="<<grid.elapsed<<" requests="<<pr<<" hits="<<ph<<" misses="<<pm<<" fills="<<pf<<" native="<<native<<std::endl;return 2;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
