#include "backing.hpp"
#include <chrono>
#include <iostream>
#include <tuple>
using namespace timing;
using Event=std::tuple<Cycle,unsigned,uint32_t,uint32_t>;
struct Result{std::vector<Event>events;uint64_t edges,requests,hits,misses,merges,fills;};
Result run(bool jump){L2Slice cache(2,4,2,4,2,1,4);Backing memory(1);Result result{};Cycle nextreq=0,limit=1000000;for(Cycle t=0;t<limit;){++result.edges;L2Input x(2);if(t==nextreq){nextreq+=71;unsigned serial=t/71;x.read[0]={true,serial+1,(serial%24)*32,255};x.read[1]={serial%3==0,serial+1,(serial%24)*32,255};x.write[0]={serial%4==0,serial+1,65536+(serial%24)*32,255};}auto y=cache.eval(x);std::vector<L2Output>offers{y};auto p=memory.prepare(t,offers);x.backing_ready=p.read_ready[0];x.store_ready=p.write_ready[0];x.backing_return=p.read_return[0];x.store_return=p.write_return[0];for(unsigned s=0;s<2;s++){if(x.read[s].valid&&y.read_ready[s])result.events.emplace_back(t,0+s,x.read[s].id,x.read[s].address);if(x.write[s].valid&&y.write_ready[s])result.events.emplace_back(t,2+s,x.write[s].id,x.write[s].address);if(y.read_valid[s])result.events.emplace_back(t,4+s,y.read_id[s],0);if(y.write_valid[s])result.events.emplace_back(t,6+s,y.write_id[s],0);}if(y.backing.valid&&x.backing_ready)result.events.emplace_back(t,8,y.backing.id,y.backing.address);if(y.store.valid&&x.store_ready)result.events.emplace_back(t,9,y.store.id,y.store.address);if(x.backing_return)result.events.emplace_back(t,10,*x.backing_return,0);if(x.store_return)result.events.emplace_back(t,11,*x.store_return,0);cache.edge(x);memory.edge(t,offers,p);Cycle n=t+1;if(jump)n=std::max(n,std::min({nextreq,cache.wake(),memory.wake(n)}));if(n>limit)n=limit;if(n>t+1){cache.advance_to(n);memory.idle_edges(n-t-1);}t=n;}result.requests=cache.requests;result.hits=cache.hits;result.misses=cache.misses;result.merges=cache.merges;result.fills=cache.fills;return result;}
int main(){auto a0=std::chrono::steady_clock::now();auto a=run(false);auto a1=std::chrono::steady_clock::now();auto b=run(true);auto a2=std::chrono::steady_clock::now();if(a.events!=b.events||a.requests!=b.requests||a.hits!=b.hits||a.misses!=b.misses||a.merges!=b.merges||a.fills!=b.fills)throw std::runtime_error("cache eventjump mismatch");std::cout<<"exact_events="<<a.events.size()<<" requests="<<a.requests<<" hits="<<a.hits<<" misses="<<a.misses<<" merges="<<a.merges<<" fills="<<a.fills<<" stepped_edges="<<a.edges<<" event_edges="<<b.edges<<" stepped_seconds="<<std::chrono::duration<double>(a1-a0).count()<<" event_seconds="<<std::chrono::duration<double>(a2-a1).count()<<'\n';}
