module output_component_top(input logic clk,rst,input logic sv,sr,sg,rg,rv,input logic[31:0]rid,
output logic ready,rsp,sc,rc,rr,output logic[31:0]response_id,read_id,read_addresses[32],output int outstanding,stores,commits,reads,completions,
input logic wv,wr,wb,wa,input logic[31:0]wid,mask,ackid,addresses[32],output logic wready,wrsp,wback,wackready,output logic[31:0]wrid,wbackid,waddress,output logic[7:0]wmask,output int sectors,
input logic av,retire,input int retire_slot,thread_count,regs,user_shared,reserved_shared,output logic aready,output int slot,resident,warps,allocregs,allocshared);
logic[31:0]zero[32],cs[4][32][8],rowwords[4][256],inputs[32];logic[255:0]data;
always_comb begin for(int l=0;l<32;l++)begin zero[l]=0;for(int w=0;w<4;w++)for(int e=0;e<8;e++)cs[w][l][e]=0;end end
studied_output_scratch_shared #(.STORE_INTERVAL(3),.STORE_RETURN_DELAY(4)) scratch(.clk,.rst,.req_valid(sv),.req_ready(ready),.req_id(32'd91),.c_registers(cs),.rsp_valid(rsp),.rsp_ready(sr),.rsp_id(response_id),.row_major_words(rowwords),.outstanding,.store_requests(stores),.store_commit_words(commits),.read_requests(reads),.read_completions(completions),.store_candidate_valid(sc),.store_grant(sg),.read_candidate_valid(rc),.read_candidate_grant(rg),.read_candidate_id(read_id),.read_candidate_byte_addresses(read_addresses),.read_candidate_input_words(inputs),.read_rsp_valid(rv),.read_rsp_ready(rr),.read_rsp_id(rid),.read_rsp_words(zero));
coalesced_fp32_warp_store store(.clk,.rst,.req_valid(wv),.req_ready(wready),.req_id(wid),.byte_addresses(addresses),.words(zero),.active_mask(mask),.rsp_valid(wrsp),.rsp_ready(wr),.rsp_id(wrid),.sector_count(sectors),.backing_req_valid(wback),.backing_req_ready(wb),.backing_req_id(wbackid),.backing_req_byte_address(waddress),.backing_req_data(data),.backing_req_word_mask(wmask),.backing_rsp_valid(wa),.backing_rsp_ready(wackready),.backing_rsp_id(ackid));
quantized_block_admission #(.BLOCK_SLOTS(11)) admission(.clk,.rst,.admit_valid(av),.admit_ready(aready),.block_threads(thread_count),.registers_per_thread(regs),.user_shared_bytes(user_shared),.reserved_shared_bytes(reserved_shared),.admitted_slot(slot),.resident_blocks(resident),.resident_warps(warps),.allocated_register_words(allocregs),.allocated_shared_bytes(allocshared),.retire_valid(retire),.retire_slot);
endmodule
