#include "sm_event.hpp"
#include <deque>
#include <iostream>
#include <chrono>
struct Event{uint64_t t;int type;uint32_t id,address,extra;bool operator==(const Event&)const=default;};
struct Result{uint64_t cycles,edges;std::vector<Event>events;};
Result run(bool jump,int contexts,int columns){sm_event::SM sm(contexts,64,columns,64);struct Ret{uint64_t due;uint32_t id;};std::deque<Ret>reads,writes;Result r{};int launched=0,done=0;uint64_t t=0;
 while(t<200000){sm_event::Input i;i.launch=launched<2*(columns/32);i.id=launched;i.row=launched/(columns/32);i.col=launched%(columns/32);i.a=4096;i.b=12288;i.c=131072;i.read_ready=t%7!=0;i.write_ready=t%11!=0;i.done_ready=t%13!=0;
 if(!reads.empty()&&reads.front().due<=t){i.read_return=reads.front().id;reads.pop_front();r.events.push_back({t,5,*i.read_return,0,0});}if(!writes.empty()&&writes.front().due<=t){i.write_return=writes.front().id;writes.pop_front();r.events.push_back({t,6,*i.write_return,0,0});}
 auto s=sm.signals(t,i);if(i.launch&&s.launch_ready){launched++;r.events.push_back({t,0,i.id,i.row,i.col});}if(s.read.valid&&i.read_ready){reads.push_back({t+31,s.read.id});r.events.push_back({t,1,s.read.id,s.read.address,0});}if(s.write.valid&&i.write_ready){writes.push_back({t+17,s.write.id});r.events.push_back({t,2,s.write.id,s.write.address,s.write.mask});}if(s.native_issue)r.events.push_back({t,3,s.native_context,s.native_pc,s.native_warp});if(s.done&&i.done_ready){done++;r.events.push_back({t,4,s.done_id,s.done_context,0});}
 sm.edge(t,i);r.edges++;if(done==2*(columns/32)){r.cycles=t+1;return r;}uint64_t next=t+1;
 if(jump){next=sm.wake(t+1);if(!reads.empty())next=std::min(next,reads.front().due);if(!writes.empty())next=std::min(next,writes.front().due);sm_event::Input probe=i;probe.read_return.reset();probe.write_return.reset();probe.read_ready=probe.write_ready=false;auto p=sm.signals(t+1,probe);if(p.read.valid||p.write.valid||p.done||launched<2*(columns/32)&&p.launch_ready)next=t+1;if(next==UINT64_MAX)throw std::runtime_error("event deadlock");next=std::max(next,t+1);}t=next;
 }throw std::runtime_error("incomplete");}
int main(int argc,char**argv){int contexts=argc>1?std::stoi(argv[1]):2,columns=contexts==11?352:96;auto t=std::chrono::steady_clock::now();auto tick=run(false,contexts,columns);double a=std::chrono::duration<double>(std::chrono::steady_clock::now()-t).count();t=std::chrono::steady_clock::now();auto event=run(true,contexts,columns);double b=std::chrono::duration<double>(std::chrono::steady_clock::now()-t).count();if(tick.cycles!=event.cycles||tick.events!=event.events){for(size_t j=0;j<std::min(tick.events.size(),event.events.size());j++)if(!(tick.events[j]==event.events[j])){std::cerr<<"SM_EVENT_FAIL index="<<j<<" tick="<<tick.events[j].t<<","<<tick.events[j].type<<" event="<<event.events[j].t<<","<<event.events[j].type<<"\n";break;}return 1;}std::cout<<"SM_EVENT_PASS cycles="<<event.cycles<<" events="<<event.events.size()<<" tick_edges="<<tick.edges<<" event_edges="<<event.edges<<" tick_seconds="<<a<<" event_seconds="<<b<<"\n";}
