#pragma once
#include "output_metadata.hpp"
namespace grid_event {
using output_event::require;using output_event::Cycle;using output_event::never;
struct Grid{
 enum State{IDLE,RUN,COMPLETE,STARTUP};State state=IDLE;int sms,rows,cols,blocks,setup_left=0,owner=-1,cursor=0,completion_cursor=0,dispatched=0,completed=0;uint64_t elapsed=0;uint32_t id=0,a=0,b=0,c=0;std::vector<bool>launched,finished;
 Grid(int ns=170,int m=2048,int n=2112):sms(ns),rows(m/32),cols(n/32),blocks(rows*cols),launched(blocks),finished(blocks){}
 struct Inputs{bool reset=false,launch=false,launch_legal=true,done_ready=false;int setup=3346,resident=0;uint32_t id=0,a=0,b=0,c=0;std::vector<bool>ready,done;std::vector<uint32_t>done_id;};
 struct Signals{bool launch_ready=false,done=false,block_launch=false,block_done=false;int launch_sm=-1,done_sm=-1;uint32_t launch_id=0,row=0,col=0,completion_id=0,completion_row=0,completion_col=0;};
 Signals signals(const Inputs&i)const{Signals s;s.launch_ready=!i.reset&&state==IDLE&&i.launch_legal;s.done=!i.reset&&state==COMPLETE;s.launch_id=dispatched;s.row=dispatched/cols;s.col=dispatched%cols;if(!i.reset&&state==RUN&&owner>=0&&dispatched<blocks){s.launch_sm=owner;s.block_launch=i.ready.at(owner);}for(int off=0;off<sms;off++){int sm=(completion_cursor+off)%sms;if(!i.reset&&state==RUN&&s.done_sm<0&&i.done.at(sm)){s.done_sm=sm;s.block_done=true;s.completion_id=i.done_id.at(sm);s.completion_row=s.completion_id/cols;s.completion_col=s.completion_id%cols;}}return s;}
 void edge(const Inputs&i){if(i.reset){int sm=sms,m=rows*32,n=cols*32;*this=Grid(sm,m,n);return;}auto s=signals(i);require(!(i.launch&&state==IDLE&&!i.launch_legal),"invalid grid launch");if(state==RUN)require(i.resident==dispatched-completed,"grid resource conservation");switch(state){case IDLE:if(i.launch&&s.launch_ready){owner=-1;cursor=completion_cursor=0;elapsed=0;id=i.id;a=i.a;b=i.b;c=i.c;dispatched=completed=0;std::fill(launched.begin(),launched.end(),false);std::fill(finished.begin(),finished.end(),false);setup_left=i.setup-1;state=i.setup>0?STARTUP:RUN;}break;case STARTUP:elapsed++;if(setup_left<=0)state=RUN;else setup_left--;break;case RUN:{elapsed++;bool wascomplete=dispatched==blocks&&completed==blocks&&i.resident==0;if(owner<0&&dispatched<blocks){int choice=-1;for(int off=0;off<sms;off++){int sm=(cursor+off)%sms;if(choice<0&&i.ready.at(sm))choice=sm;}if(choice>=0)owner=choice;}if(s.block_launch){cursor=(owner+1)%sms;owner=-1;require(dispatched<blocks&&!launched[dispatched],"grid duplicate dispatch");launched[dispatched]=true;dispatched++;}if(s.block_done){completion_cursor=(s.done_sm+1)%sms;require(s.completion_id<uint32_t(blocks)&&launched[s.completion_id]&&!finished[s.completion_id],"grid invalid completion");finished[s.completion_id]=true;completed++;}if(wascomplete)state=COMPLETE;break;}case COMPLETE:if(i.done_ready)state=IDLE;break;}}
 Cycle wake(Cycle now)const{if(state==STARTUP)return now+1;if(state==RUN&&dispatched==blocks&&completed==blocks)return now+1;return never;}
 void skip_startup(Cycle edges){require(state==STARTUP&&edges<=uint64_t(std::max(setup_left,0)),"grid skip crosses startup transition");setup_left-=edges;elapsed+=edges;}
};
}
